"""init

Revision ID: 0ca9c1ad8f2b
Revises: b5ec58e7fea9
Create Date: 2024-11-20 21:43:26.800620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca9c1ad8f2b'
down_revision = 'b5ec58e7fea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'telegram_user', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_user', type_='unique')
    op.drop_column('task', 'chat_id')
    # ### end Alembic commands ###
