"""init

Revision ID: 54028c632908
Revises: e1c1007f6c64
Create Date: 2024-11-20 02:06:12.250019

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54028c632908"
down_revision = "e1c1007f6c64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_user", sa.Column("extra_balance", sa.Numeric(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_user", "extra_balance")
    # ### end Alembic commands ###
