"""init

Revision ID: 7e1b9e77f7ab
Revises: ab804ae47820
Create Date: 2024-11-18 10:19:14.724027

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e1b9e77f7ab"
down_revision = "ab804ae47820"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_user", sa.Column("last_days_active", sa.BigInteger(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_user", "last_days_active")
    # ### end Alembic commands ###
