"""init

Revision ID: ab804ae47820
Revises: e40cbcb5a2b5
Create Date: 2024-11-18 10:11:11.257888

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab804ae47820"
down_revision = "e40cbcb5a2b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_user", sa.Column("days_active", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "telegram_user",
        sa.Column(
            "last_action",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_user", "last_action")
    op.drop_column("telegram_user", "days_active")
    # ### end Alembic commands ###
