"""init

Revision ID: c22def4485a5
Revises: 88f9c59d6d63
Create Date: 2024-11-18 04:18:35.551992

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c22def4485a5"
down_revision = "88f9c59d6d63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_user", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_user",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    # ### end Alembic commands ###
