"""init

Revision ID: c62c9b33c8d9
Revises: 7e1b9e77f7ab
Create Date: 2024-11-18 20:43:41.143910

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c62c9b33c8d9"
down_revision = "7e1b9e77f7ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_user",
        sa.Column("last_daily_reward", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_user", "last_daily_reward")
    # ### end Alembic commands ###
