"""init

Revision ID: e1c1007f6c64
Revises: c62c9b33c8d9
Create Date: 2024-11-19 23:33:44.581465

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1c1007f6c64"
down_revision = "c62c9b33c8d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "telegram_user_referrer_id_fkey", "telegram_user", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "telegram_user",
        "telegram_user",
        ["referrer_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "telegram_user", type_="foreignkey")
    op.create_foreign_key(
        "telegram_user_referrer_id_fkey",
        "telegram_user",
        "telegram_user",
        ["referrer_id"],
        ["telegram_id"],
    )
    # ### end Alembic commands ###
