"""init

Revision ID: e40cbcb5a2b5
Revises: b5b157df4a6d
Create Date: 2024-11-18 09:44:32.801410

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e40cbcb5a2b5"
down_revision = "b5b157df4a6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_user", sa.Column("referrer_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "telegram_user", sa.Column("referrals", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "telegram_user", sa.Column("tickets", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "telegram_user",
        "telegram_user",
        ["referrer_id"],
        ["telegram_id"],
        ondelete="NO ACTION",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "telegram_user", type_="foreignkey")
    op.drop_column("telegram_user", "tickets")
    op.drop_column("telegram_user", "referrals")
    op.drop_column("telegram_user", "referrer_id")
    # ### end Alembic commands ###
